---
- name: Set the defaults here otherwise they can't be overriden in the same play if the role is called twice
  set_fact:
    es_repo_name: "{{ es_major_version }}"

- name: Use the oss repo and package if requested
  set_fact:
    es_repo_name: "{{ 'oss-' + es_major_version }}"
    kibana_package_name: "kibana-oss"
  when:
    - kibana_install_oss
