---
- name: Ensure libselinux-python on CentOS 6.x
  become: yes
  yum: name=libselinux-python state=present update_cache=yes
  when: ansible_distribution is match("CentOS") and ansible_distribution_major_version is match("6")

- name: RedHat - add Elasticsearch repo
  become: yes
  template: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch-{{ es_repo_name }}.repo
  when: es_use_repository

- name: RedHat - include versionlock
  include: kibana-RedHat-version-lock.yml
  when: kibana_version_lock

- name: RedHat - Remove non oss package if the old elasticsearch package is installed
  become: yes
  yum:
    name: 'kibana'
    state: 'absent'
  when: kibana_package_name == 'kibana-oss'

- name: RedHat - Install Elasticsearch
  become: yes
  yum:
    name: '{{ es_package_name }}{% if es_version is defined and es_version != ""  %}-{{ es_version }}{% endif %}'
    state: present
    update_cache: yes
  when: es_use_repository
  register: redhat_elasticsearch_install_from_repo
  notify: restart elasticsearch
  until: redhat_elasticsearch_install_from_repo.rc == 0
  retries: 5
  delay: 10
  environment:
    ES_PATH_CONF: "/etc/elasticsearch"

- name: RedHat - Install Kibana from url
  become: yes
  yum: name={% if kibana_custom_package_url is defined %}{{ kibana_custom_package_url }}{% else %}{{ kibana_package_url }}-{{ es_version }}-x86_64.rpm{% endif %} state=present
  when: not es_use_repository
  register: kibana_install_from_package
  notify: restart kibana
